name: "build"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Install cookiecutter
        run: |
          pip install cookiecutter
      - name: Test cookiecutter
        run: |
          cookiecutter . --no-input
